#!/bin/bash

set -euo pipefail

if grep -qEi "(Microsoft|WSL)" /proc/version *> /dev/null; then
	echo "Running on Microsoft Windows Subsystem for Linux. Setting Environment Variable VAGRANT_WSL_ENABLE_WINDOWS_ACCESS=\"1\""
	export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
	echo "Removing Vagrantfile and copying Vagrantfile-wsl to Vagrantfile."
	rm Vagrantfile
	cp Vagrantfile-WSL Vagrantfile

else
	echo "Running on GNU/Linux."
	echo "Removing Vagrantfile and copying Vagrantfile-linux to Vagrantfile."
	rm Vagrantfile
	cp Vagrantfile-linux Vagrantfile
fi


readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${dir}/../"
trap 'popd' EXIT

./scripts/distclean
./scripts/generate-certs
./scripts/generate-kubeconfig-kube-proxy
./scripts/generate-kubeconfig-worker
./scripts/generate-kubeconfig-controller-manager
./scripts/generate-cni-config
./scripts/generate-service-files
./scripts/download-tools
if $VAGRANT_WSL_ENABLE_WINDOWS_ACCESS
then
      	vagrant up --parallel --provider=hyperv
else
	vagrant up --parallel
fi
./scripts/setup-etcd
./scripts/setup-controller-services
./scripts/configure-kubectl-on-host
./scripts/setup-kubelet-api-cluster-role
./scripts/setup-worker-services
echo -e "\033[1mFinished. Cluster should be healthy and soon in state ready:\033[0m"
kubectl get componentstatuses
kubectl get nodes
kubectl apply -f manifests/coredns.yaml
